trigger:
  paths:
    exclude:
    - docs/*
    - README.md
    - History.md

pr:
  paths:
    exclude:
    - docs/*
    - README.md
    - History.md

jobs:
  - template: windows-jobs-template.yml
    parameters:
      name: 'Windows_VS2017_x64'
      image: 'vs2017-win2016'
      platform: 'x64'
      vcpkgTriplet: "x64-windows"

  - template: windows-jobs-template.yml
    parameters:
      name: 'Windows_VS2017_Win32'
      image: 'vs2017-win2016'
      platform: 'Win32'
      vcpkgTriplet: "x86-windows"

  - template: windows-jobs-template.yml
    parameters:
      name: 'Windows_VS2019_x64'
      image: 'windows-2019'
      platform: 'x64'
      vcpkgTriplet: "x64-windows"

  - template: windows-jobs-template.yml
    parameters:
      name: 'Windows_VS2019_Win32'
      image: 'windows-2019'
      platform: 'Win32'
      vcpkgTriplet: "x86-windows"

  - template: unix-jobs-template.yml
    parameters:
      name: 'Ubuntu_GCC_8'
      image: 'ubuntu-18.04'
      installToolsCmd: 'sudo apt-get install gcc-8 g++-8'
      vcpkgTriplet: "x64-linux"
      cmakeGenArgs: '-DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8'

  - template: unix-jobs-template.yml
    parameters:
      name: 'Ubuntu_GCC_9'
      image: 'ubuntu-latest'
      installToolsCmd: 'sudo apt-get install gcc-8 g++-8'
      vcpkgTriplet: "x64-linux"
      cmakeGenArgs: '-DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9'

  - template: unix-jobs-template.yml
    parameters:
      name: 'Ubuntu_Clang_8'
      image: 'ubuntu-latest'
      installToolsCmd: 'sudo apt-get install clang-8'
      vcpkgTriplet: "x64-linux"
      cmakeGenArgs: '-DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8'

  - template: unix-jobs-template.yml
    parameters:
      name: 'MacOS_AppleClang_12'
      image: 'macOS-10.15'
      vcpkgTriplet: "x64-osx"
      vcpkgCacheDir: "/Users/runner/.cache/vcpkg/archives/"
      cmakeGenArgs: '-DBUILD_RAPIDYAML_ARCHIVE=OFF'
